### ISSUE TITLE
Use any-promise instead of bluebird

### ISSUE THREAD

**Issue by RangerMauve** [spion/promise-streams#11]
It'd be handy to not be forced to use bluebird to use promises with streams. For instance, in the cases where just the native promise implementation would be enough, or if people were already using a different promise library.

[any-promise](https://github.com/kevinbeaty/any-promise) automagically detects what promise configuration your library user wants to use.

**Comment by petkaantonov** [comment]
The code is using methods that are only in bluebird

**Comment by RangerMauve** [comment]
Ah. Makes sense.
