### ISSUE TITLE
No ps.filter

### ISSUE THREAD

**Issue by joepie91** [spion/promise-streams#4]
It seems like a `filter` method is missing. It's possible to implement it manually using `through` of course, but it'd be nicer if that weren't necessary :)

**Comment by spion** [comment]
Fixed in 761aa2d70d2d08da0eb1eeda89f37d8ecf763b95

**Comment by joepie91** [comment]
Thanks!

Should probably update the repository description, though, it currently still says:

> A collection of node.js streams that work well with promises (through, map, reduce)
